# Generated by Django 4.2.6 on 2023-10-17 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BoardUser",
        ),
    ]
