# Generated by Django 4.2.6 on 2023-10-22 09:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0003_comment_remove_ad_price_boarduser"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="price",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="ad",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
