# Generated by Django 4.2.6 on 2023-10-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_category_adcategory_ad_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='users',
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
