# Generated by Django 4.2.6 on 2023-10-26 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0010_remove_ad_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='categories',
            field=models.CharField(choices=[('TN', 'Танки'), ('DD', 'ДД'), ('HL', 'Хиллы'), ('ME', 'Торговцы'), ('GM', 'Гилдмастера'), ('QG', 'Квестгиверы'), ('BS', 'Кузнецы'), ('TS', 'Кожевники'), ('PM', 'Зельевары'), ('SM', 'Мастера заклинаний')], default=0, max_length=2),
            preserve_default=False,
        ),
    ]
