# Generated by Django 4.2.6 on 2023-10-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_ad_author_ad_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='created_at',
            field=models.DateTimeField(default=1),
        ),
    ]
